apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: enterprise-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: enterprise-routing
spec:
  hosts:
    - "*"
  gateways:
    - enterprise-gateway
  http:
    - match:
        - uri:
            prefix: /auth
      route:
        - destination:
            host: auth-service
            port:
              number: 6000
    - match:
        - uri:
            prefix: /payments
      route:
        - destination:
            host: payments-service
            port:
              number: 7000
    - match:
        - uri:
            prefix: /backend
      route:
        - destination:
            host: backend-service
            port:
              number: 5000
